# Generated by Django 6.0.2 on 2026-02-17 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('check_interval', models.IntegerField(default=60, help_text='seconds')),
                ('timeout', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], max_length=10)),
                ('response_time_ms', models.FloatField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitor.servicetarget')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['service', '-checked_at'], name='monitor_che_service_fb907e_idx')],
            },
        ),
    ]
